# Generated by Django 4.2.30 on 2026-07-15 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='N8nConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_url', models.URLField(verbose_name=django.db.models.fields.URLField)),
                ('api_key', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='n8n_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('workflow_id', models.CharField(blank=True, max_length=255)),
                ('workflow_url', models.URLField(blank=True)),
                ('documentation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('n8n_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='workflows.n8nconnection')),
            ],
        ),
    ]
